volumes:
  pg_data_production:
  static_volume:
  media:

services:
  db:
    restart: on-failure
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: annabera/foodgram_backend:latest 
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media:/app/media
    depends_on: 
      - db
  frontend:
    image: annabera/foodgram_frontend:latest 
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: annabera/foodgram_gateway:latest
    env_file: .env
    depends_on: 
      - backend
      - frontend
    volumes:
      - static_volume:/staticfiles/
      - media:/app/media
    ports:
      - 9500:80