version: '3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.10 
    env_file: .env 
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    env_file: .env
    build: ./gateway/
    depends_on:
      - backend
      - frontend
      - db
    ports:
      - 10000:80
    volumes:
      - static:/staticfiles/
      - media:/app/media