version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: daniyaralzhanov/foodgram_backend
    hostname: backend
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/static/
      - media:/app/media/

  frontend:
    image: daniyaralzhanov/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: daniyaralzhanov/foodgram_gateway
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/staticfiles/
      - media:/app/media/
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend


