MAX_LENGTH_OF_FIRST_NAME = 150
MAX_LENGTH_OF_LAST_NAME = 150
MAX_LENGTH_OF_PASS = 150
MAX_LENGTH_OF_INGREDIENT = 50
MAX_LENGTH_OF_UNIT = 10
MAX_LENGTH_OF_TAG = 25
MAX_LENGTH_OF_TAG_SLUG = 25
MAX_LENGTH_OF_RECIPE = 200
