# Generated by Django 3.2.3 on 2024-08-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20240806_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(upload_to='recipes/images/', verbose_name='Фото рецепта'),
        ),
    ]
