# Generated by Django 3.2.3 on 2024-08-06 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_alter_recipes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartingredients',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shopping', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
