"""Project's constants."""

BASE_USER_FIELDS_LIMIT = 6
MAX_LENGTH_OF_USERNAME = MAX_LENGTH_OF_FIRST_NAME = 150
MAX_LENGTH_OF_EMAIL = 254
MAX_LENGTH_OF_LAST_NAME = 150
MESSAGE_FOR_USERNAME_VALIDATOR = ('Только буквы и цифры')
MAX_LENGTH_OF_TAG = MAX_LENGTH_OF_TAG_SLUG = 32
MAX_LENGTH_OF_INGREDIENT = 128
MAX_LENGTH_OF_UNIT = 64
MAX_LENGTH_OF_RECIPE = MIN_LENGTH_OF_FAVOURITE = 256
MIN_TIME_OF_COOKING = MIN_VALUE_OF_INGREDIENTS = 1
MAX_TIME_OF_COOKING = MAX_VALUE_OF_INGREDIENTS = 32767
EMPTY_VALUE = 'blank'
SYMBOLS_FOR_SHORT_LINK = ('ABCDEFGHJKLMNOPQRSTUVWXabcdefghijkmnopqrstuvwx')
SHORT_LINK_LENGTH = 6
SHORTCODE_MIN = 4
SHORTCODE_MAX = 20
